#sample of project configuration
#
selenium:
  grid: false
  gridServer: 'http://192.168.35.34:4444/wd/hub'
  implicitwaits: 30
  
browser:
  size: 'maximize'  # '1024*768', etc.
  type: 'chrome'
  autoClose: true
  
webdriver:
  chrome:
    driver: 'src/test/resources/drivers/chrome/2.45/chromedriver.exe'
    bin: ''
    args:
      - 'no-sandbox'
      #- 'headless' 
      #- 'disable-gpu'
      #- 'proxy-server=proxy:8080'
      #- 'user-data-dir=C:/temp/profile'
    extensions:
      - ''
      #- 'C:/temp/proxy.zip'
    downloadDirectory: ''
  firefox:
    driver: 'src/test/resources/drivers/firefox/0.23.0/geckodriver.exe'
    bin: ''
    profile: '' 
  ie:
    driver: ''

log:
  level: 'INFO'  

  